### ISSUE TITLE
Unable to run the command provided to install.

### ISSUE THREAD

**Issue by wilsonwan** [catppuccin/windows-files#9]
`. { Invoke-WebRequest -UseBasicParsing https://github.com/catppuccin/windows-files/raw/main/install.ps1 } | iex`

The command above gives me the follow error after choosing whether If i want to use flat appearance or not.

![image](https://github.com/catppuccin/windows-files/assets/42862478/2a73dd12-6b8e-437c-bb40-d7928216b38a)

**Comment by coteyka1209** [comment]
**i have the same problem**

**Comment by ygordreyer-starloop** [comment]
Same problem here.

**Comment by kkingstoun** [comment]
Me too

**Comment by RIPPERONInCHEEZ** [comment]
> `. { Invoke-WebRequest -UseBasicParsing https://github.com/catppuccin/windows-files/raw/main/install.ps1 } | iex`
> 
> The command above gives me the follow error after choosing whether If i want to use flat appearance or not.
> 
> ![image](https://private-user-images.githubusercontent.com/42862478/309204961-2a73dd12-6b8e-437c-bb40-d7928216b38a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODk3OTEsIm5iZiI6MTcwOTc4OTQ5MSwicGF0aCI6Ii80Mjg2MjQ3OC8zMDkyMDQ5NjEtMmE3M2RkMTItNmI4ZS00MzdjLWJiNDAtZDc5MjgyMTZiMzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA1MzEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxY2M0NGE0MmFkMDg4NTVlM2I5YzQzMzlhM2IyNDAxMGRjOTlmOGFjYWVmZmFkYThjZDA1ZjUyNGMwZThkYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lJNbj-middmJvzZi-4dDCAd8SxrPmw_8y-x6SEwbKpU)

same issue here as well

![image](https://github.com/catppuccin/windows-files/assets/60893966/09acb56e-9f9a-44e6-b90f-6a802f1ecb26)

**Comment by mukiturrahman** [comment]
Same issue here as well, did anyone find a solution to it?

**Comment by mukiturrahman** [comment]
@wilsonwan @coteyka1209 @ygordreyer-starloop @RIPPERONInCHEEZ 

I have fixed the problem and submitted a pull request. Here is the link, please check it out:  [ https://github.com/catppuccin/windows-files/pull/10 ]

**Comment by RIPPERONInCHEEZ** [comment]
> @wilsonwan @coteyka1209 @ygordreyer-starloop @RIPPERONInCHEEZ
> 
> I have fixed the problem and submitted a pull request. Here is the link, please check it out: [ https://github.com/[/pull/10](https://github.com/catppuccin/windows-files/pull/10) ]

I tried that fix and it was still giving me the Configuration files not found error sadly. :/

**Comment by DakshG07** [comment]
Could anyone getting this error please supply the actual location of their configuration folder?

**Comment by mukiturrahman** [comment]
You need to download the Files application from Microsoft Store

Here is the download link [Files](https://files.community/docs/contributing/updates)

**Comment by Wakers** [comment]
Same issue for me. Also it seems that the files app removed it's theming capability in an update at some point?

**Comment by sgoudham** [comment]
Hi, I've merged #10 which should hopefully resolve the issues that you are seeing with newer versions of windows-files. 

Could someone confirm that the latest version of `install.ps1` from the main branch works? If not, then windows-files may have changed how the config folder is stored and will require extra troubleshooting.

**Comment by seidmadur** [comment]
Still experiencing issues using the latest version from the main branch.
![image](https://github.com/catppuccin/windows-files/assets/67888904/06641e87-9de2-405a-865e-dd6b6cdf462f)

**Comment by sgoudham** [comment]
Hey @ricowalker,

That error is actually because the [-AsHashtable](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-json?view=powershell-7.2#parameters) parameter used in the script was introduced in Powershell 6.0, leading me to believe that your powershell is below that version. 

I will update the documentation to mention that this is the minimum required version, could you try [updating your powershell ](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/migrating-from-windows-powershell-51-to-powershell-7?view=powershell-7.4#installing-powershell-7)and see if it works then? 

Manual instructions have not been provided because manual application of the colour schemes proves to be very tedious and annoying.

**Comment by m-wynn** [comment]
I am also seeing this issue on Powershell 7

![image](https://github.com/catppuccin/windows-files/assets/2483388/74b8c667-19e5-4dbf-837c-83376193b2f9)

Fixed!

**Comment by Atrament1s** [comment]
Make sure you have the [files app](https://github.com/catppuccin/windows-files) downloaded AND are on PowerShell 7. Doing so worked for me.

**Comment by sgoudham** [comment]
Going to close this issue now as I believe the initial error should be fixed now. If anyone in this thread comes across other installation issues, please create a new one!
